### ISSUE TITLE
Installing HSARuntime instructions

### ISSUE THREAD

**Issue by davidbp** [jpsamaroo/HSARuntime.jl#11]
In the README it is stated we need to install
```
ROCR
ROCT
```

Do you mean the two projects in this links?
```
https://github.com/RadeonOpenCompute/ROCR-Runtime
https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface
```

**Comment by jpsamaroo** [comment]
Yes, that is correct. I'll update the README to link to those directly. Note that if your OS provides these packages for you, then you should try to use them unless they're some really old version (ROCm is at v2.4 right now, so <2.0 is "old" to me, although it'll likely still work fine). Let me know if you run into issues with this!

EDIT: README has been updated with links and some extra details.

**Comment by jpsamaroo** [comment]
Closing this for now, feel free to file a new issue if you run into any other issues :slightly_smiling_face:
