### ISSUE TITLE
Remove compat constraint for CEnum?

### ISSUE THREAD

**Issue by wsphillips** [jpsamaroo/HSARuntime.jl#33]
https://github.com/jpsamaroo/HSARuntime.jl/blob/e6a64ebff4c45ed09e729d077245040e97f069e4/Project.toml#L12

Do we need to restrict this? Or can we at least bump to 0.4?

**Comment by vchuravy** [comment]
We need to restrict for automatic tagging but we should be able to include `0.3` and `0.4`. Generally we should install CompatHelper.jl
